server:
  port: 8080

spring:
  application:
    name: movie-search-api
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:26016/movies
  artemis:
    mode: embedded
    broker-url: tcp://localhost:9876
    user: admin
    password: secret

springdoc:
  api-docs:
    path: /spec
  swagger-ui:
    path: /doc

logging:
  level:
    org:
      dk.cygni: info
      apache.activemq: error
      springdoc: info
      springframework.boot: info

